import sys

def patch_js():
    with open("static/js/part-form.js", "a", encoding="utf-8") as f:
        f.write("\n")
        f.write("/* ── Attachments ─────────────────────────────────────────────────────────────*/\n")
        f.write("async function loadAttachments(partId) {\n")
        f.write("  if (!partId || partId === '—') return;\n")
        f.write("  const list = document.getElementById('attachments-list');\n")
        f.write("  if (!list) return;\n")
        f.write("  \n")
        f.write("  try {\n")
        f.write("    const res = await fetch(`/api/parts/${encodeURIComponent(partId)}/attachments`);\n")
        f.write("    const data = await res.json();\n")
        f.write("    if (!data.length) {\n")
        f.write("      list.innerHTML = '<div class=\"muted small\">No attachments found.</div>';\n")
        f.write("      return;\n")
        f.write("    }\n")
        f.write("    \n")
        f.write("    list.innerHTML = `<table class=\"data-table\" style=\"margin-top: 8px;\">\n")
        f.write("      <thead><tr><th>Filename</th><th style=\"text-align:right; width:60px;\">Size</th><th style=\"width:40px;\"></th></tr></thead>\n")
        f.write("      <tbody>\n")
        f.write("        ${data.map(a => `\n")
        f.write("          <tr>\n")
        f.write("            <td><a href=\"/attachments/${a.id}\" target=\"_blank\">${escapeHtml(a.original_filename)}</a></td>\n")
        f.write("            <td class=\"small text-right\">${(a.size_bytes / 1024).toFixed(1)} KB</td>\n")
        f.write("            <td style=\"text-align:center;\">\n")
        f.write("              <button type=\"button\" class=\"btn btn-ghost btn-sm\" style=\"color:var(--danger); padding:2px 6px;\" onclick=\"deleteAttachment('${a.id}', '${partId}')\" title=\"Delete\">✕</button>\n")
        f.write("            </td>\n")
        f.write("          </tr>\n")
        f.write("        `).join('')}\n")
        f.write("      </tbody>\n")
        f.write("    </table>`;\n")
        f.write("  } catch (e) {\n")
        f.write("    list.innerHTML = '<div class=\"alert-error\">Error loading attachments.</div>';\n")
        f.write("  }\n")
        f.write("}\n\n")

        f.write("async function uploadAttachment(partId, inputEl) {\n")
        f.write("  if (!inputEl.files || !inputEl.files[0]) return;\n")
        f.write("  const file = inputEl.files[0];\n")
        f.write("  if (file.size > 50 * 1024 * 1024) {\n")
        f.write("    showToast('File too large (max 50MB)', 'error');\n")
        f.write("    inputEl.value = '';\n")
        f.write("    return;\n")
        f.write("  }\n")
        f.write("  \n")
        f.write("  const fd = new FormData();\n")
        f.write("  fd.append('file', file);\n")
        f.write("  \n")
        f.write("  const list = document.getElementById('attachments-list');\n")
        f.write("  if (list) list.innerHTML = '<div class=\"muted small\">Uploading...</div>';\n")
        f.write("  \n")
        f.write("  const res = await apiFetch(`/api/parts/${encodeURIComponent(partId)}/attachments`, fd);\n")
        f.write("  inputEl.value = '';\n")
        f.write("  if (res.ok) {\n")
        f.write("    showToast('File uploaded', 'success');\n")
        f.write("    loadAttachments(partId);\n")
        f.write("  } else {\n")
        f.write("    showToast(res.msg || 'Upload failed', 'error');\n")
        f.write("    loadAttachments(partId);\n")
        f.write("  }\n")
        f.write("}\n\n")

        f.write("async function deleteAttachment(attId, partId) {\n")
        f.write("  if (!confirm('Delete this attachment?')) return;\n")
        f.write("  const res = await apiFetch(`/api/attachments/${encodeURIComponent(attId)}`, null, 'DELETE');\n")
        f.write("  if (res.ok) {\n")
        f.write("    showToast('Deleted', 'success');\n")
        f.write("    loadAttachments(partId);\n")
        f.write("  } else {\n")
        f.write("    showToast(res.msg || 'Delete failed', 'error');\n")
        f.write("  }\n")
        f.write("}\n")

if __name__ == "__main__":
    patch_js()
