import sys

def patch_js():
    with open("static/js/project-detail.js", "a", encoding="utf-8") as f:
        f.write("\n")
        f.write("/* ── Project Attachments Modal ──────────────────────────────────────────────*/\n")
        f.write("async function showProjectAttachments(projId) {\n")
        f.write("  const backdrop = document.getElementById('attachments-modal-backdrop');\n")
        f.write("  const body     = document.getElementById('attachments-modal-body');\n")
        f.write("  \n")
        f.write("  body.innerHTML = '<div style=\"padding:40px;text-align:center;color:var(--text2)\">Loading…</div>';\n")
        f.write("  backdrop.classList.add('open');\n")
        f.write("  \n")
        f.write("  try {\n")
        f.write("    const res  = await fetch(`/api/projects/${encodeURIComponent(projId)}/attachments`);\n")
        f.write("    const data = await res.json();\n")
        f.write("    \n")
        f.write("    if (!data || !data.length) {\n")
        f.write("      body.innerHTML = '<div style=\"padding:40px;text-align:center;color:var(--text2)\">No attachments found in this project\\'s BOM.</div>';\n")
        f.write("      return;\n")
        f.write("    }\n")
        f.write("    \n")
        f.write("    body.innerHTML = `<table class=\"data-table\">\n")
        f.write("      <thead><tr><th style=\"width:150px\">Part ID</th><th>Filename</th><th style=\"text-align:right; width:80px;\">Size</th><th style=\"text-align:right; width:120px;\">Uploaded</th></tr></thead>\n")
        f.write("      <tbody>\n")
        f.write("        ${data.map(a => `\n")
        f.write("          <tr>\n")
        f.write("            <td class=\"mono small\"><a href=\"/parts/${encodeURIComponent(a.part_id)}/edit\" target=\"_blank\">${escapeHtml(a.part_id)}</a></td>\n")
        f.write("            <td><a href=\"/attachments/${a.id}\" target=\"_blank\">${escapeHtml(a.original_filename)}</a></td>\n")
        f.write("            <td class=\"small text-right\">${(a.size_bytes / 1024).toFixed(1)} KB</td>\n")
        f.write("            <td class=\"small text-right\">${a.uploaded_at.split(' ')[0]}</td>\n")
        f.write("          </tr>\n")
        f.write("        `).join('')}\n")
        f.write("      </tbody>\n")
        f.write("    </table>`;\n")
        f.write("  } catch (e) {\n")
        f.write("    body.innerHTML = `<div style=\"padding:40px;text-align:center;color:var(--red)\">Failed to load attachments.</div>`;\n")
        f.write("  }\n")
        f.write("}\n")

if __name__ == "__main__":
    patch_js()
